PSPSDK=$(shell psp-config --pspsdk-path)
PSPDIR=$(shell psp-config --psp-prefix)
TARGET_LIB = ../libbufferedio.a
OBJS = 	bufferedio.o
INCDIR = 
CFLAGS = -O2 -G0 -fomit-frame-pointer -fPIC
CXXFLAGS = $(CFLAGS) -fno-rtti
ASFLAGS = $(CFLAGS)

include $(PSPSDK)/lib/build.mak


